openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample Password Flow OAuth2 Project
  description: This is an example of using OAuth2 Password Flow.

paths:
  /auth:
    post:
      tags:
      - auth
      summary: Return JWT token
      operationId: apis.authcontroller.auth_token
      parameters:
      - name: name
        in: query
        description: user name for login
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: user password for login
        required: true
        schema:
          type: string
      responses:
        '200':
          description: JWT token
          content:
            text/plain:
              schema:
                type: string
  /secret:
    get:
      tags:
      - auth
      summary: Return secret string
      operationId: apis.authcontroller.get_secret
      responses:
        '200':
          description: secret response
          content:
            text/plain:
              schema:
                type: string
      security:
        - bearerAuth: ['secret']
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        password:
          type: string
      required:
        - name
        - password
  securitySchemes:
     bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
        x-bearerInfoFunc: apis.authcontroller.auth_token
